from collections.abc import Mapping
from typing import Any, Optional


class RESTClient:
    headers: Mapping[str, str]
    _session: Any
    _base_url: str

    def __init__(self, api_key: str) -> None: ...

    def get_market_status(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_ticker_details(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_ticker_news(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
